### ISSUE TITLE
Updates on this library? 

### ISSUE THREAD

**Issue by nicecraftz** [ErrorxCode/JxInsta#18]
Hello, are there any updates on this library? ì
I have seen it has been called a continuation of **Instagram4J** but I cannot make it work

https://gist.github.com/nicecraftz/287ffd4e3437ac8b96f26cd86d4a0455

I am getting this error just when creating the instance of JxInsta with valid credentials.
`Exception in thread "main" java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at com.errorxcode.jxinsta.Utils.getCrsf(Utils.java:100)
	at com.errorxcode.jxinsta.JxInsta.<init>(JxInsta.java:71)
	at it.alessandrocalista.Main.main(Main.java:22)`

**Comment by ErrorxCode** [comment]
Please also share the code to reproduce the issue. What type of authentication were you using?

**Comment by ErrorxCode** [comment]
Is it happening only in WEB_AUTHENTICATION mode?

**Comment by nicecraftz** [comment]
Really sorry for the no reply about this issue, will try tomorrow if i happen to remember it, lol.

sorry again.

**Comment by ErrorxCode** [comment]
It's okey, lemme know

**Comment by nicecraftz** [comment]
> It's okey, lemme know

totally forgot about this once again, i will try in the morning, just put it into my calendar to remember it, lol.

**Comment by nicecraftz** [comment]
Hallo, sorry for the long awaited response
```java
public static void main(String[] args) {
        try {
            JxInsta insta = new JxInsta(
                    "#####",
                    "#####",
                    JxInsta.LoginType.BOTH_WEB_AND_APP_AUTHENTICATION
            );
            File file = new File("test.jpg");
            insta.uploadStory(file);
        } catch (IOException | InstagramException e) {
            throw new RuntimeException(e);
        }
        System.out.println("Hello, World!");
    }
```
This is my current snippet, it should publish a story with the following test.jpg image but instead its giving me out this error.

```text
Exception in thread "main" java.lang.IndexOutOfBoundsException: Empty list doesn't contain element at index 0.
	at kotlin.collections.EmptyList.get(Collections.kt:36)
	at kotlin.collections.EmptyList.get(Collections.kt:24)
	at com.errorxcode.jxinsta.Utils.getCrsf(Utils.java:100)
	at com.errorxcode.jxinsta.JxInsta.<init>(JxInsta.java:71)
	at com.errorxcode.jxinsta.JxInsta.<init>(JxInsta.java:77)
	at it.alessandrocalista.instagram.Main.main(Main.java:12)
```

**Comment by ErrorxCode** [comment]
Change the LoginType to **WEB_AUTH** and try again, after that change it to **MOBILE_AUTH** and try again. Let me know the error in both cases

**Comment by cboldon** [comment]
I also get the same issue (exact same stack). I've tried all available auth types.

**Comment by ErrorxCode** [comment]
Alright, Please wait for the update!

**Comment by ErrorxCode** [comment]
Thank you for drawing attention to the issue. I'll counter this in the new release (Coming soon)
